name: Update README with my latest coding stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-Readme:
    name: Automatically update my README  
    runs-on: ubuntu-latest
    steps:
      - uses: tariksahni/coding-stats-wakatime@v1.0.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_MONTHLY: true
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTION: ${{ github.action }}
